name: correctink
description: CorrectInk is a study app with tasks and flashcards.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.9.1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  realm: 1.2.0
  path_provider: ^2.0.10
  go_router: ^6.5.8
  objectid: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.0-nullsafety
  flutter_local_notifications: ^15.1.0+1
  connectivity_plus: ^4.0.0
  auto_size_text: ^3.0.0
  flutter_reorderable_list: ^1.3.1
  localization: ^2.1.0
  rxdart: ^0.27.7
  timezone: ^0.9.2
  permission_handler: ^10.4.3
  markdown: ^7.1.1
  flutter_markdown: ^0.6.17
  url_launcher: ^6.1.12
  http: ^0.13.6
  easy_stepper: ^0.7.3
  back_button_interceptor: ^7.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  csv: ^5.0.2
  file_picker: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/correctink_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/correctink_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/correctink_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/correctink_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true


  assets:
    - assets/config/
    - assets/i18n/
    - assets/icon/

