import 'package:flutter/material.dart';

import 'default_theme.dart';

class BlueTheme implements DefaultTheme{
static  const lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF2C5DA7),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFD7E3FF),
    onPrimaryContainer: Color(0xFF001B3F),
    secondary: Color(0xFF565E71),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFDAE2F9),
    onSecondaryContainer: Color(0xFF131C2B),
    tertiary: Color(0xFF705574),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFAD8FD),
    onTertiaryContainer: Color(0xFF29132E),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFDFBFF),
    onBackground: Color(0xFF1A1B1F),
    surface: Color(0xFFFDFBFF),
    onSurface: Color(0xFF1A1B1F),
    surfaceVariant: Color(0xFFE0E2EC),
    onSurfaceVariant: Color(0xFF44474E),
    outline: Color(0xFF74777F),
    onInverseSurface: Color(0xFFF2F0F4),
    inverseSurface: Color(0xFF2F3033),
    inversePrimary: Color(0xFFABC7FF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF2C5DA7),
    outlineVariant: Color(0xFFC4C6D0),
    scrim: Color(0xFF000000),
  );
static  const darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFABC7FF),
    onPrimary: Color(0xFF002F65),
    primaryContainer: Color(0xFF03458E),
    onPrimaryContainer: Color(0xFFD7E3FF),
    secondary: Color(0xFFBEC6DC),
    onSecondary: Color(0xFF283041),
    secondaryContainer: Color(0xFF3E4759),
    onSecondaryContainer: Color(0xFFDAE2F9),
    tertiary: Color(0xFFDDBCE0),
    onTertiary: Color(0xFF3F2844),
    tertiaryContainer: Color(0xFF573E5C),
    onTertiaryContainer: Color(0xFFFAD8FD),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xFF1A1B1F),
    onBackground: Color(0xFFE3E2E6),
    surface: Color(0xFF1A1B1F),
    onSurface: Color(0xFFE3E2E6),
    surfaceVariant: Color(0xFF44474E),
    onSurfaceVariant: Color(0xFFC4C6D0),
    outline: Color(0xFF8E9099),
    onInverseSurface: Color(0xFF1A1B1F),
    inverseSurface: Color(0xFFE3E2E6),
    inversePrimary: Color(0xFF2C5DA7),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFABC7FF),
    outlineVariant: Color(0xFF44474E),
    scrim: Color(0xFF000000),
  );

/*static const lightColorScheme = ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xFF006874),
        onPrimary: Color(0xFFFFFFFF),
        primaryContainer: Color(0xFF97F0FF),
        onPrimaryContainer: Color(0xFF001F24),
        secondary: Color(0xFF4A6267),
        onSecondary: Color(0xFFFFFFFF),
        secondaryContainer: Color(0xFFCDE7EC),
        onSecondaryContainer: Color(0xFF051F23),
        tertiary: Color(0xFF525E7D),
        onTertiary: Color(0xFFFFFFFF),
        tertiaryContainer: Color(0xFFDAE2FF),
        onTertiaryContainer: Color(0xFF0E1B37),
        error: Color(0xFFBA1A1A),
        errorContainer: Color(0xFFFFDAD6),
        onError: Color(0xFFFFFFFF),
        onErrorContainer: Color(0xFF410002),
        background: Color(0xFFFAFDFD),
        onBackground: Color(0xFF191C1D),
        surface: Color(0xFFFAFDFD),
        onSurface: Color(0xFF191C1D),
        surfaceVariant: Color(0xFFDBE4E6),
        onSurfaceVariant: Color(0xFF3F484A),
        outline: Color(0xFF6F797A),
        onInverseSurface: Color(0xFFEFF1F1),
        inverseSurface: Color(0xFF2E3132),
        inversePrimary: Color(0xFF4FD8EB),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFF006874),
        outlineVariant: Color(0xFFBFC8CA),
        scrim: Color(0xFF000000),
    );

   static const darkColorScheme = ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xFF4FD8EB),
        onPrimary: Color(0xFF00363D),
        primaryContainer: Color(0xFF004F58),
        onPrimaryContainer: Color(0xFF97F0FF),
        secondary: Color(0xFFB1CBD0),
        onSecondary: Color(0xFF1C3438),
        secondaryContainer: Color(0xFF334B4F),
        onSecondaryContainer: Color(0xFFCDE7EC),
        tertiary: Color(0xFFBAC6EA),
        onTertiary: Color(0xFF24304D),
        tertiaryContainer: Color(0xFF3B4664),
        onTertiaryContainer: Color(0xFFDAE2FF),
        error: Color(0xFFFFB4AB),
        errorContainer: Color(0xFF93000A),
        onError: Color(0xFF690005),
        onErrorContainer: Color(0xFFFFDAD6),
        background: Color(0xFF191C1D),
        onBackground: Color(0xFFE1E3E3),
        surface: Color(0xFF191C1D),
        onSurface: Color(0xFFE1E3E3),
        surfaceVariant: Color(0xFF3F484A),
        onSurfaceVariant: Color(0xFFBFC8CA),
        outline: Color(0xFF899294),
        onInverseSurface: Color(0xFF191C1D),
        inverseSurface: Color(0xFFE1E3E3),
        inversePrimary: Color(0xFF006874),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFF4FD8EB),
        outlineVariant: Color(0xFF3F484A),
        scrim: Color(0xFF000000),
    );*/

}